development:
  git_app: 'C:\Git\bin\git.exe'
  git_project_root: 'C:\Work\CourseWeb\repositories\git\'
  git_repositories_root: 'C:\Work\CourseWeb\repositories\'
  url: 'http://127.0.0.1:3000'
test:
  git_app: /usr/bin/git
  git_project_root: /home/red/Work/CourseWeb/repositories/git/
  git_repositories_root: /home/red/Work/CourseWeb/repositories/
production:
  git_app: /usr/bin/git
  git_project_root: /home/red/Work/CourseWeb/repositories/git/
  git_repositories_root: /home/red/Work/CourseWeb/repositories/