development:
  git_app: /usr/bin/git
  git_project_root: /home/red/Work/CourseWeb/repositories/git/
  git_repositories_root: /home/red/Work/CourseWeb/repositories/
test:
  git_app: /usr/bin/git
  git_project_root: /home/red/Work/CourseWeb/repositories/git/
  git_repositories_root: /home/red/Work/CourseWeb/repositories/
production:
  git_app: /usr/bin/git
  git_project_root: /home/red/Work/CourseWeb/repositories/git/
  git_repositories_root: /home/red/Work/CourseWeb/repositories/