development:
  git_app: C:\Git\bin\git.exe
  git_project_root: C:\Work\CourseWeb\repositories\
test:
  git_app: C:\Git\bin\git.exe
  git_project_root: C:\Work\CourseWeb\repositories\
production:
  git_app: C:\Git\bin\git.exe
  git_project_root: C:\Work\CourseWeb\repositories\
